### ISSUE TITLE
Only use the selection modal

### ISSUE THREAD

**Issue by acki** [jameelmoses/acf-flexible-content-extended#4]
Hi there

Is it possible to use only the modal for the element selection, but edit then the layout normal (aka not in the modal)?

Thanks,
Christoph

**Comment by jameelmoses** [comment]
Yep! To not use the modal for editing, you can use [https://github.com/jameelmoses/acf-flexible-content-preview](https://github.com/jameelmoses/acf-flexible-content-preview)

**Comment by acki** [comment]
Thanks!

**Comment by romanklabal** [comment]
Hi Jameel, as you closed the standalone plugin, is there another way to just do the previews? Maybe a filter, or remove_action? Thanks!
